import json

from slack_chargebee_notifier.main import handler

if __name__ == '__main__':

    #sqs_stuff = {"id": "ev_16BjqDSQlZCGWKpR", "occurred_at": 1614928926, "source": "admin_console", "user": "kaitlyn@oep.com", "object": "event", "api_version": "v2", "content": {"subscription": {"id": "AzqYVlSQlYm8p18b", "billing_period": 1, "billing_period_unit": "month", "customer_id": "AzZl4ESQlSmkBtl", "status": "active", "current_term_start": 1614928826, "current_term_end": 1614928926, "created_at": 1614928826, "started_at": 1614928826, "activated_at": 1614928826, "cancelled_at": 1614928926, "updated_at": 1614928926, "has_scheduled_changes": False, "resource_version": 1614928926405, "deleted": False, "object": "subscription", "currency_code": "AUD", "subscription_items": [{"item_price_id": "npaq-ft-m", "item_type": "plan", "quantity": 1, "unit_price": 4100, "amount": 4100, "free_quantity": 0, "object": "subscription_item"}], "due_invoices_count": 0, "mrr": 0}, "customer": {"id": "AzZl4ESQlSmkBtl", "first_name": "Vijeet", "last_name": "Agrawal", "email": "xyz@gmail.com", "auto_collection": "on", "net_term_days": 0, "allow_direct_debit": False, "created_at": 1614927398, "created_from_ip": "3.233.249.52", "taxability": "taxable", "updated_at": 1614928459, "locale": "en", "pii_cleared": "active", "resource_version": 1614928459022, "deleted": False, "object": "customer", "billing_address": {"country": "IN", "validation_status": "not_validated", "object": "billing_address"}, "card_status": "valid", "promotional_credits": 0, "refundable_credits": 0, "excess_payments": 0, "unbilled_charges": 0, "preferred_currency_code": "AUD", "primary_payment_source_id": "pm_AzZl4ESQlVjJn16f", "payment_method": {"object": "payment_method", "type": "card", "reference_id": "tok_AzZl4ESQlVjJT16e", "gateway": "chargebee", "gateway_account_id": "gw_1mbDWgbR0vSsLof9T", "status": "valid"}}, "card": {"status": "valid", "gateway": "chargebee", "gateway_account_id": "gw_1mbDWgbR0vSsLof9T", "first_name": "oep", "last_name": "Chargebee", "iin": "411111", "last4": "1111", "card_type": "visa", "funding_type": "credit", "expiry_month": 12, "expiry_year": 2022, "created_at": 1614928100, "updated_at": 1614928100, "resource_version": 1614928100153, "object": "card", "masked_number": "************1111", "customer_id": "AzZl4ESQlSmkBtl", "payment_source_id": "pm_AzZl4ESQlVjJn16f"}}, "event_type": "subscription_cancelled", "webhook_status": "not_applicable", "webhooks": [{"id": "whv2_16BjsPSQfvdGn4Qs", "webhook_status": "succeeded", "object": "webhook"}, {"id": "whv2_AzZm2iSNvzaGV3x4", "webhook_status": "not_applicable", "object": "webhook"}]}

    the_event = dict(
        Records=[dict(body=json.dumps(sqs_stuff))],
    )
    the_context = None
    resp = handler(the_event, the_context)
